### ISSUE TITLE
Can't build on Ubuntu 16.04

### ISSUE THREAD

**Issue by homm** [DarthSim/imgproxy#10]
```
$ cat /etc/issue
Ubuntu 16.04.2 LTS

$ go version
go version go1.6.2 linux/amd64

$ vips --version
vips-8.2.2-Sat Jan 30 17:12:08 UTC 2016
```

Geting the following:

```
$ go get -f -u github.com/DarthSim/imgproxy
# github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg
In file included from go/src/github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg/vips.go:5:0:
go/src/github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg/vips.h: In function ‘vips_reduce_bridge’:
go/src/github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg/vips.h:125:9: warning: implicit declaration of function ‘vips_reduce’ [-Wimplicit-function-declaration]
  return vips_reduce(in, out, xshrink, yshrink, NULL);
         ^
# github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg
/tmp/go-build499020947/github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg/_obj/vips.cgo2.o: In function `vips_reduce_bridge':
go/src/github.com/DarthSim/imgproxy/vendor/github.com/h2non/bimg/vips.h:125: undefined reference to `vips_reduce'
collect2: error: ld returned 1 exit status
```

Is there any minimal required version of go or libvips?

**Comment by DarthSim** [comment]
Hi! Could you check the latest version of the code? I removed some dependencies with redundant links, now it should be (theoretically) compatible with libvips 7.41.0+.

**Comment by homm** [comment]
@DarthSim How fails with `undefined reference to 'vips_gifload_buffer'`

**Comment by DarthSim** [comment]
Oh, looks like libvips <8.3 doesn't support gif. I removed gif support for old versions of vips and tried it on my Ubuntu 16.04,  it builds fine now.

**Comment by homm** [comment]
Confirmed. Thank you!
